DATALOADER:
  SIZE_DIVISIBILITY: 32
INPUT:
  TO_BGR255: False
  PIXEL_MEAN: [0.485, 0.456, 0.406]
  PIXEL_STD: [0.229, 0.224, 0.225]
MODEL:
  BACKBONE:
    CONV_BODY: "HRNET-HR"
    OUT_CHANNELS: 256
  NECK:
    IN_CHANNELS:
      - 32
      - 64
      - 128
      - 256
    OUT_CHANNELS: 256
    POOLING: "AVG"
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "hrnet_imagenet_pretrained/hrnetv2_w32_imagenet_pretrained.pth"
  RPN:
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
  HRNET:
    STAGE1:
      NUM_CHANNELS:
      - 64
      NUM_BLOCKS:
      - 4
      BLOCK: 'BottleneckWithFixedBatchNorm'
    STAGE2:
      NUM_MODULES: 1
      NUM_BRANCHES: 2
      NUM_BLOCKS:
      - 4
      - 4
      NUM_CHANNELS:
      - 32
      - 64
      BLOCK: 'BasicBlockWithFixedBatchNorm'
      FUSE_METHOD: 'SUM'
    STAGE3:
      NUM_MODULES: 4
      NUM_BRANCHES: 3
      NUM_BLOCKS:
      - 4
      - 4
      - 4
      NUM_CHANNELS:
      - 32
      - 64
      - 128
      BLOCK: 'BasicBlockWithFixedBatchNorm'
      FUSE_METHOD: 'SUM'
    STAGE4:
      NUM_MODULES: 3
      NUM_BRANCHES: 4
      NUM_BLOCKS:
      - 4
      - 4
      - 4
      - 4
      NUM_CHANNELS: 
      - 32
      - 64
      - 128
      - 256
      BLOCK: 'BasicBlockWithFixedBatchNorm'
      FUSE_METHOD: 'SUM'
  ROI_HEADS:
    USE_FPN: True
    BATCH_SIZE_PER_IMAGE: 512
    POSITIVE_FRACTION: 0.25
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
  ROI_MASK_HEAD:
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    FEATURE_EXTRACTOR: "MaskRCNNFPNFeatureExtractor"
    PREDICTOR: "MaskRCNNC4Predictor"
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 2
    RESOLUTION: 28
    SHARE_BOX_FEATURE_EXTRACTOR: False
  MASK_ON: True
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
SOLVER:
  BASE_LR: 0.02
  WEIGHT_DECAY: 0.0001
  STEPS: (150000, 170000)
  MAX_ITER: 180000
OUTPUT_DIR: "work_dirs/mask_rcnn_hrnet_w32_2x"
